# Generated by Django 4.0.2 on 2022-05-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist', '0004_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(upload_to='staticfiles/%Y/%m/%d'),
        ),
    ]
