# Generated by Django 4.0.2 on 2022-05-29 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('craigslist', '0005_alter_announcement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL),
        ),
    ]
