# Generated by Django 4.0.2 on 2022-05-29 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('craigslist', '0007_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='buyer', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='seller', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
